### ISSUE TITLE
项目引用了com.fasterxml.jackson.core:jackson-databind@2.9.9等84个开源组件，存在12个严重漏洞，建议升级

### ISSUE THREAD

**Issue by AbbyWoo** [buxia97/RuleApi#1]
大佬，我看你这个项目引用了com.fasterxml.jackson.core:jackson-databind@2.9.9等84个开源组件，存在12个严重漏洞，建议你升级下。
```
漏洞标题：FasterXML jackson-databind 代码问题漏洞
漏洞描述：
FasterXML Jackson是美国FasterXML公司的一款适用于Java的数据处理工具。jackson-databind是其中的一个具有数据绑定功能的组件。
FasterXML jackson-databind 2.9.10之前版本中存在代码问题漏洞。攻击者可利用该漏洞执行代码。
国家漏洞库信息：https://www.cnvd.org.cn/flaw/show/CNVD-2019-37174
漏洞级别：严重
影响范围：[2.9.0, 2.9.10)
最小修复版本：2.9.10
引入路径：
com.RuleApi:RuleApi:1.0.0-SNAPSHOT->com.qcloud:cos_api@5.6.8->com.fasterxml.jackson.core:jackson-databind@2.9.9
```
其它还有11个严重漏洞 ，信息有点多我就不贴了，你自己看下完整报告：https://www.murphysec.com/j?p=a44833

**Comment by buxia97** [comment]
感谢反馈，我会尽快做升级处理，



---- 回复的原邮件 ----
| 发件人 | Abby ***@***.***> |
| 日期 | 2022年01月07日 02:19 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [buxia97/RuleApi] ***@***.***等84个开源组件，存在12个严重漏洞，建议升级 (Issue #1) |

***@***.***等84个开源组件，存在12个严重漏洞，建议你升级下。

漏洞标题：FasterXML jackson-databind 代码问题漏洞
漏洞描述：
FasterXML Jackson是美国FasterXML公司的一款适用于Java的数据处理工具。jackson-databind是其中的一个具有数据绑定功能的组件。
FasterXML jackson-databind 2.9.10之前版本中存在代码问题漏洞。攻击者可利用该漏洞执行代码。
国家漏洞库信息：https://www.cnvd.org.cn/flaw/show/CNVD-2019-37174
漏洞级别：严重
影响范围：[2.9.0, 2.9.10)
最小修复版本：2.9.10
引入路径：
***@***.******@***.***

其它还有11个严重漏洞 ，信息有点多我就不贴了，你自己看下完整报告：https://www.murphysec.com/j?p=a44833

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by buxia97** [comment]
已经全部修复，其中jackson-databind的一个漏洞可能为误报，因为官方源显示当前的版本不存在漏洞，而墨菲安全的提示反而是让我下降到有漏洞的版本。



在 2022-01-07 08:19:49，"Abby Wu" ***@***.***> 写道：

***@***.***等84个开源组件，存在12个严重漏洞，建议你升级下。

漏洞标题：FasterXML jackson-databind 代码问题漏洞
漏洞描述：
FasterXML Jackson是美国FasterXML公司的一款适用于Java的数据处理工具。jackson-databind是其中的一个具有数据绑定功能的组件。
FasterXML jackson-databind 2.9.10之前版本中存在代码问题漏洞。攻击者可利用该漏洞执行代码。
国家漏洞库信息：https://www.cnvd.org.cn/flaw/show/CNVD-2019-37174
漏洞级别：严重
影响范围：[2.9.0, 2.9.10)
最小修复版本：2.9.10
引入路径：
***@***.******@***.***


其它还有11个严重漏洞 ，信息有点多我就不贴了，你自己看下完整报告：https://www.murphysec.com/j?p=a44833

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AbbyWoo** [comment]
我们check下
