### ISSUE TITLE
很棒的项目

### ISSUE THREAD

**Issue by yegetables** [buxia97/RuleApi#2]
你好，我是一名大二学生，最近学习了ssm，本来想自己写个blog的demo，将原来typecho的主题移植到自己写的demo里面的。做个前后端分离。
可是typecho是php写的，我用的那个主题也是内嵌php。想前后端分离+restful分格的api+json ，然后不是很知道需要什么api，翻typecho的文档也是没找到。
我发现这个项目提供了我的需求，还没没看源码，猜测可能是直接使用typecho的数据库，然后自己做MVC。
目前是想贡献这个项目，但可能能力不是很足，也不知道开发者愿不愿意交流下？？
~~看了看作者的经历，好像只比我大一点，但是太牛逼了。膜拜~~

**Comment by buxia97** [comment]
我这个项目也是属于一时兴起，基于typecho的数据库完成了一套API的扩展。如果你想出力的话，我非常欢迎，因为我也是近几个月才开始学习springboot，这个项目也是成果之一，而且一个人开发确实少了一些乐趣。
你可以加入这个qq群，我们一起交流:776176904
