### ISSUE TITLE
初始化数据库脚本在哪啊？？？

### ISSUE THREAD

**Issue by zhengfenwei** [buxia97/RuleApi#3]
点击web初次安装及更新执行时 返回：Typecho未安装或者数据表前缀不正确，请尝试安装typecho或者修改properties配置文件。

**Comment by zhengfenwei** [comment]
> 点击web初次安装及更新执行时 返回：Typecho未安装或者数据表前缀不正确，请尝试安装typecho或者修改properties配置文件。
这个好像是缺少出示user表..

**Comment by zhengfenwei** [comment]
![image](https://user-images.githubusercontent.com/7141804/183230952-bce0196e-7452-48e7-b01e-7e4569eaac64.png)

**Comment by zhengfenwei** [comment]
![image](https://user-images.githubusercontent.com/7141804/183230958-d6717b88-d0ae-46b6-8e41-cd25dceaa440.png)

**Comment by buxia97** [comment]
这个是基于typecho的API程序，你使用前需要先安装typecho或者导入typecho的数据表，它们的官网是https://typecho.org/。
如果你已经安装了typecho，则直接修改配置文件，让数据库和typecho网站的一致即可。
另外，我也在尝试构建独立数据库的版本，但现在还未更新。

**Comment by zhengfenwei** [comment]
初始化脚本在这：https://github.com/typecho/typecho/tree/master/install
